remote_theme: pmarsceill/just-the-docs

title: Mazaka Yazılım Eticaret Dokümantasyonu
description: Mazaka Yazılım eticaret paketleri için dokümantasyon sistemi

footer_content: 'Copyright &copy; <a href="https://www.mazakayazilim.com">Mazaka Yazılım</a>'

last_edit_timestamp: false
gh_edit_link: false

plugins:
    - jekyll-seo-tag
